### ISSUE TITLE
Is this package not working?

### ISSUE THREAD

**Issue by ayame113** [atom-community/atom-ide-signature-help#64]
I'm sorry if this was the expected behavior.

When I installed this package, I noticed that nothing was executed because it didn't contain the dist folder.
![image](https://user-images.githubusercontent.com/40050810/115220272-4eb07500-a143-11eb-9289-071c793c5388.png)

I found the build script commented out. Is this intentional?
https://github.com/atom-community/atom-ide-signature-help/blob/626b292d659b8340809805a0afac5c794c0bd712/.github/workflows/CI.yml#L74-L77

---
By the way, when I ran the following command, the package worked.👍
```bash
cd %HOMEPATH%\.atom\packages\atom-ide-signature-help
npm install rollup-plugin-atomic
npm install rollup
rollup -c
```
![image](https://user-images.githubusercontent.com/40050810/115219428-7c48ee80-a142-11eb-8fc6-44adc17cb604.png)

**Comment by aminya** [comment]
I released a new version. Hopefully, that fixes the issue.

**Comment by ayame113** [comment]
This package works fine now. Thank you!
